function ML = triangle_quad(Bl,s,psi1,psi2,psi3,areal,p_I)
ML = ( 8*areal*areal/((4-2*s)*(3-2*s)*(2-2*s)) ).*reshape(...
    psi1*( (  sum( (Bl*[p_I'; ones(1,length(p_I))]).^2 ).^(-1-s) )' ) +...
    psi2*( (  sum( (Bl*[ones(1,length(p_I)) ; p_I']).^2 ).^(-1-s) )' ) + ...
    psi3*( (  sum( (Bl*[p_I' ; p_I' - ones(1,length(p_I))]).^2 ).^(-1-s) )' ) , 3 , 3);
end
